name: Pytest API
on:
  push:
    branches: [ main, master, httpx_api ]
  pull_request:
    branches: [ main, master, httpx_api  ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run your tests
        run: python -m pytest --alluredir=allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure_report
          path: allure-results/
